// client/widget.solid/src/contexts/Language.jsx
import {
  createContext,
  useContext,
  createSignal,
  createEffect,
  onCleanup,
} from 'solid-js';
import { omit } from 'ramda';

import { useCookie } from '@/hooks/useCookie';

// ----------------------
// LanguageContext
// ----------------------

export const LanguageContext = createContext([
  'en',
  {
    setLanguage: () => {},
  },
]);

// ----------------------
// LanguageProvider
// ----------------------

export const LanguageProvider = props => {
  const [cookie, setCookie] = useCookie('locale', 'en');
  const [language, setLanguage] = createSignal(cookie || 'en');

  const _set_language = lang => {
    window.PubSub.publish('language', {
      payload: {
        language: lang,
      },
    });
  };

  const _onmessage = (msg, data) => {
    const lang = data?.payload?.language;
    if (msg && msg === 'language' && lang) {
      setLanguage(lang);
      setCookie(lang);
    }
  };

  createEffect(() => {
    window.PubSub.subscribe('language', _onmessage);
  });

  onCleanup(() => {
    window.PubSub.unsubscribe('language');
  });

  const value = [
    language(),
    {
      setLanguage: _set_language,
    },
  ];

  return (
    <LanguageContext.Provider value={value} {...omit(['children'], props)}>
      {props.children}
    </LanguageContext.Provider>
  );
};

// client/widget.react/src/contexts/Language.jsx
import React, {
  useContext,
  createContext,
  useEffect,
  useCallback,
} from 'react';
import { useTranslation } from 'react-i18next';

import { COOKIE_BASE_NAME } from '@/constants';
import { useCookie } from '@/hooks/useCookie';

// ----------------------
// LanguageContext
// ----------------------

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
});

// ----------------------
// LanguageProvider
// ----------------------

export const LanguageProvider = props => {
  const { i18n, t } = useTranslation();
  const [cookie, setCookie] = useCookie('locale', 'en');

  const _setLanguage = useCallback(locale => {
    i18n.changeLanguage(locale);
    setCookie(locale);
  }, []);

  return (
    <LanguageContext.Provider
      value={{
        language: i18n?.language,
        setLanguage: _setLanguage,
        i18n,
        t,
      }}
      {...props}
    />
  );
};

// ----------------------
// useLanguage
// ----------------------

export const useLanguage = () => useContext(LanguageContext);
