// client/widget.solid/src/components/language.jsx
import { useContext, createSignal, createEffect, Show, on } from 'solid-js';
// import tw from 'twin.macro';

import { EmotionContext } from '@/contexts/Emotion';
import { LanguageContext } from '@/contexts/Language';

const createStyles = ({ css }) => {
  return {
    base: css`
      display: inline-block;
      width: 90px;
    `,
  };
};

export const Language = props => {
  const [language, { setLanguage }] = useContext(LanguageContext);
  const [emotion] = useContext(EmotionContext);
  const [styles, setStyles] = createSignal(null);

  const _set_language = (e, lang) => {
    e.stopPropagation();
    setLanguage(lang);
  };

  createEffect(() => {
    if (emotion()) {
      setStyles(createStyles(emotion()));
    }
  });

  return (
    <Show when={emotion() && styles() && language()} fallback={<div></div>}>
      {(({ cx }) => (
        <>
          <img
            src="images/flag_us.png"
            class="language-button language-button-first"
            className={cx(styles().base)}
            onClick={e => _set_language(e, 'en')}
          />

          <img
            src="images/flag_jp.png"
            class="language-button language-button-second"
            className={cx(styles().base)}
            onClick={e => _set_language(e, 'ja')}
          />
        </>
      ))(emotion())}
    </Show>
  );
};

// client/widget.react/src/components/language.jsx
import React, { useCallback } from 'react';
import tw, { css } from 'twin.macro';

import { useLanguage } from '@/contexts/Language';

const styles = {
  base: css`
    display: inline-block;
    width: 36px;
  `,
};

export const Language = ({ styles: extra }) => {
  const { language, setLanguage } = useLanguage();

  const _setLanguage = useCallback((e, language) => {
    e.stopPropagation();
    setLanguage(language);
  }, []);

  return (
    <>
      <img
        src="images/flag_us.png"
        css={[styles.base, extra?.base, extra?.first]}
        onClick={e => _setLanguage(e, 'en')}
      />

      <img
        src="images/flag_jp.png"
        css={[styles.base, extra?.base, extra?.second]}
        onClick={e => _setLanguage(e, 'ja')}
      />
    </>
  );
};
