// client/widget.react/src/widgets/translate.jsx
import React, { useState, useEffect } from 'react';
import sanitizeHtml from 'sanitize-html';
// import tw, { css } from 'twin.macro';

import { run_all } from '@/lib/service';
import { capitalize, decode } from '@/lib/utils';
import { LanguageProvider, useLanguage } from '@/contexts/Language';

const makeDictionary = (html, dataset) => {
  let dict = null;

  if (html && dataset) {
    const fallback = dataset['lang'] || 'en';

    dict = { fallback };

    dict[fallback] = html ? html.trim() : '';

    ['en', 'ja'].forEach(lang => {
      if (lang !== fallback) {
        const value = dataset[`lang${capitalize(lang)}`];
        if (value) {
          dict[lang] = decode(value);
        }
      }
    });
  }

  return dict;
};

const Translate = ({ innerHTML, dataset }) => {
  const { language: lang, i18n, t } = useLanguage();
  const [dict, setDict] = useState(null);
  const [content, setContent] = useState(null);

  useEffect(() => {
    if (!dict) {
      setDict(makeDictionary(innerHTML, dataset));
    }
  }, [innerHTML]);

  useEffect(() => {
    if (dict) {
      const value = dict[lang] || dict[dict.fallback];
      if (value) {
        setContent(value);
      }
    }
  }, [dict, lang]);

  return (
    !!content && (
      <span
        dangerouslySetInnerHTML={{ __html: content }}
        className="translate-content"
      ></span>
    )
  );
};

run_all('[data-lang]', <Translate />, [[LanguageProvider]]);

// client/widget.solid/src/widgets/translate.jsx
import { register, compose } from 'component-register';
import { withSolid } from 'solid-element';
import {
  useContext,
  createSignal,
  createEffect,
  createMemo,
  Show,
  onCleanup,
} from 'solid-js';
import { createStore } from 'solid-js/store';
import tw from 'twin.macro';
// import sanitizeHtml from 'sanitize-html';

import { capitalize, decode } from '@/lib/utils';
import { EmotionContext, EmotionProvider } from '@/contexts/Emotion';
import { WorkerProvider } from '@/contexts/Worker';
import { LanguageProvider, useLanguageWorker } from '@/contexts/Language';

const makeDict = (html, dataset) => {
  let res;
  if (html && dataset) {
    const fallback = dataset['lang'] || 'en';
    res = {
      ready: true,
      fallback,
      [fallback]: html ? html.trim() : '',
    };
    ['en', 'ja'].forEach(lang => {
      if (lang !== fallback) {
        const value = dataset[`lang${capitalize(lang)}`];
        if (value) {
          const decoded = decode(value);
          res[lang] = decoded;
        }
      }
    });
  }
  return res;
};

const createStyles = ({ css }) => {
  return {
    content: css`
      display: inline;
    `,
  };
};

const Translate = props => {
  const [emotion] = useContext(EmotionContext);
  const [styles, setStyles] = createSignal(null);
  const [languageworker] = useLanguageWorker();
  const [dict, setDict] = createStore({
    ready: false,
    fallback: 'en',
    en: '',
    ja: '',
  });

  const { innerHTML, dataset } = props?.element || {};
  const language = createMemo(() => languageworker.language());

  createEffect(() => {
    if (emotion()) {
      const { cx, css } = emotion();
      setStyles({
        content: cx(createStyles(emotion()), dataset?.css && css(dataset.css)),
      });
    }
  });

  createEffect(() => {
    if (!dict.ready) {
      const _dict = makeDict(innerHTML, dataset);
      if (_dict) {
        setDict(_dict);
      }
    }
  });

  return (
    <Show
      when={emotion() && styles() && dict.ready && languageworker.ready()}
      fallback={<div></div>}
    >
      {(({ cx }) => (
        <div class="translate-content" className={cx(styles().content)}>
          {dict[language()]}
        </div>
      ))(emotion())}
    </Show>
  );
};

compose(
  register('translate-widget'),
  withSolid
)((props, options) => {
  const element = options?.element;

  return (
    <WorkerProvider>
      <LanguageProvider>
        <EmotionProvider key="translate" element={element}>
          <Translate element={element} {...props} />
        </EmotionProvider>
      </LanguageProvider>
    </WorkerProvider>
  );
});
