// client/widget.solid/src/widgets/breadcrumbs.jsx
import { customElement } from 'solid-element';
import {
  useContext,
  createSignal,
  createEffect,
  createMemo,
  Show,
} from 'solid-js';
// import { createStore } from 'solid-js/store';
import tw from 'twin.macro';

import { EmotionContext, EmotionProvider } from '@/contexts/Emotion';
import { LanguageContext, LanguageProvider } from '@/contexts/Language';
import { createSharedStyles } from '@/styles';

import { Sep } from '@/components/sep';

const createStyles = ({ css }) => {
  const shared = createSharedStyles({ css, list: ['linkStyle'] });

  return {
    content: css`
      ${tw`
        w-full flex flex-row justify-start items-center
        text-xl font-bold text-gray-900
      `}
    `,
    link: css`
      ${shared.linkStyle}
      ${tw`
        text-gray-900
        link:text-gray-900 link:no-underline link:font-normal
        hover:text-gray-900 hover:no-underline hover:font-normal
        visited:text-gray-900 visited:no-underline visited:font-normal
      `}
    `,
    sep: css`
      ${tw`mx-2`}
    `,
  };
};

const Breadcrumbs = props => {
  const [emotion] = useContext(EmotionContext);
  const [styles, setStyles] = createSignal(null);
  const [language] = useContext(LanguageContext);
  const [breadcrumbs, setBreadcrumbs] = createSignal([]);

  const lastindex = createMemo(() => breadcrumbs().length - 1);

  createEffect(() => {
    if (emotion()) {
      setStyles(createStyles(emotion()));
    }
  });

  createEffect(() => {
    const { dataset } = props?.element || {};

    if (dataset?.breadcrumbs) {
      try {
        const arr = JSON.parse(dataset.breadcrumbs);
        setBreadcrumbs(arr);
      } catch (err) {
        console.warn(err);
      }
    }
  });

  return (
    <Show
      when={emotion() && styles() && language() && lastindex() > -1}
      fallback={<div></div>}
    >
      {(({ cx, css }) => (
        <nav id="breadcrumbs-content" className={cx(styles().content)}>
          {breadcrumbs().map((bread, i) => {
            const [text, link] = bread;
            const show = i < lastindex();

            return link ? (
              <a key={i} href={link} className={cx(styles().link)}>
                {text}
                {show && <Sep styles={cx(styles().sep)} />}
              </a>
            ) : (
              <div key={i}>
                {text}
                {show && <Sep styles={cx(styles().sep)} />}
              </div>
            );
          })}
        </nav>
      ))(emotion())}
    </Show>
  );
};

customElement('breadcrumbs-widget', {}, (props, { element }) => {
  return (
    <LanguageProvider>
      <EmotionProvider key="breadcrumbs" element={element}>
        <Breadcrumbs element={element} {...props} />
      </EmotionProvider>
    </LanguageProvider>
  );
});

// client/widget.react/src/widgets/breadcrumbs.jsx
import React, { useState, useEffect } from 'react';
import tw, { css } from 'twin.macro';

import { run } from '@/lib/service';
import { Sep } from '@/components/sep';
import { linkStyle } from '@/styles';

const styles = {
  content: tw`
    w-full flex flex-row justify-start items-center
    text-xl font-bold text-gray-900
  `,
  link: css`
    ${linkStyle}
    ${tw`
      text-gray-900
      link:text-gray-900 link:no-underline link:font-normal
      hover:text-gray-900 hover:no-underline hover:font-normal
      visited:text-gray-900 visited:no-underline visited:font-normal
    `}
  `,
};

const Breadcrumbs = ({ dataset }) => {
  const [breadcrumbs, setBreadcrumbs] = useState([]);

  useEffect(() => {
    if (dataset?.breadcrumbs) {
      try {
        const arr = JSON.parse(dataset.breadcrumbs);
        setBreadcrumbs(arr);
      } catch (err) {
        console.warn(err);
      }
    }
  }, [dataset?.breadcrumbs]);

  const lastindex = breadcrumbs.length - 1;

  return (
    <div id="breadcrumbs-content" css={styles.content}>
      {lastindex > -1 &&
        breadcrumbs.map((bread, i) => {
          const [text, link] = bread;
          const show = i < lastindex;

          return link ? (
            <a key={i} href={link} css={styles.link}>
              {text}
              {show && <Sep styles={tw`mx-2`} />}
            </a>
          ) : (
            <div key={i}>
              {text}
              {show && <Sep styles={tw`mx-2`} />}
            </div>
          );
        })}
    </div>
  );
};

run('#breadcrumbs', <Breadcrumbs />);
