// client/widget.solid/src/widgets/language.jsx
import { customElement } from 'solid-element';
import { useContext, createSignal, createEffect, Show } from 'solid-js';
import moment from 'moment';
import tw from 'twin.macro';

import { EmotionContext, EmotionProvider } from '@/contexts/Emotion';
import { LanguageProvider } from '@/contexts/Language';
import { Language as LanguageComponent } from '@/components/language';

const createStyles = ({ css }) => {
  return {
    container: css`
      display: inline;
      ${tw`flex flex-row justify-center items-center`}
      .language-button {
        width: 36px;
      }
      .language-button-second {
        ${tw`ml-2`}
      }
    `,
  };
};

const Language = props => {
  const [emotion] = useContext(EmotionContext);
  const [styles, setStyles] = createSignal(null);
  const [datetime, setDatetime] = createSignal(null);

  createEffect(() => {
    if (emotion()) {
      setStyles(createStyles(emotion()));
    }
  });

  createEffect(() => {
    if (!datetime()) {
      const _dt = props?.element?.dataset?.datetime;
      if (_dt) {
        const dt = moment(_dt);
        console.log(
          '[widget/Language] datetime:',
          dt.format('YYYY-MM-DD HH:mm:ss')
        );
        setDatetime(dt);
      }
    }
  });

  return (
    <Show when={emotion() && styles()} fallback={<div></div>}>
      {(({ cx }) => (
        <div className={styles().container}>
          <LanguageComponent {...props} />
        </div>
      ))(emotion())}
    </Show>
  );
};

customElement('language-widget', {}, (props, { element }) => {
  return (
    <LanguageProvider>
      <EmotionProvider key="language" element={element}>
        <Language element={element} {...props} />
      </EmotionProvider>
    </LanguageProvider>
  );
});

// client/widget.react/src/widgets/language.jsx
import React, { useState, useEffect } from 'react';
import moment from 'moment';
import tw, { css } from 'twin.macro';

import { run_all } from '@/lib/service';
import { LanguageProvider } from '@/contexts/Language';
import { Language as LanguageComponent } from '@/components/language';

const styles = {
  container: tw`inline flex flex-row justify-center items-center`,
  language: {
    base: css`
      width: 36px;
    `,
    second: tw`ml-2`,
  },
};

export const Language = ({ dataset, styles: extra }) => {
  const [datetime, setDatetime] = useState(null);

  useEffect(() => {
    if (!datetime) {
      const _dt = dataset?.datetime;
      if (_dt) {
        const dt = moment(_dt);
        console.log(
          '[widget/Language] datetime:',
          dt.format('YYYY-MM-DD HH:mm:ss')
        );
        setDatetime(dt);
      }
    }
  }, [dataset?.datetime]);

  return (
    <div css={styles.container}>
      <LanguageComponent styles={styles.language} />
    </div>
  );
};

run_all('[data-language]', <Language />, [[LanguageProvider]]);
