// client/widget.react/src/contexts/Worker.js
import React, { useContext, createContext, useState, useEffect } from 'react';

// ----------------------
// WorkerContext
// ----------------------

const WorkerContext = createContext({
  worker: null,
});

// ----------------------
// WorkerProvider
// ----------------------

export const WorkerProvider = (props = {}) => {
  const [worker, setWorker] = useState(null);

  useEffect(() => {
    if (!worker) {
      setWorker(
        new SharedWorker(
          /* webpackChunkName: "worker" */ new URL('@/worker', import.meta.url)
        )
      );
    }

    return () => {
      if (worker) {
        worker.close();
        setWorker(null);
      }
    };
  }, []);

  return <WorkerContext.Provider value={{ worker }} {...props} />;
};

// ----------------------
// useWorker
// ----------------------

export const useWorker = () => useContext(WorkerContext);

// client/widget.solid/src/contexts/Worker.js
import { createContext, createSignal, createEffect, onCleanup } from 'solid-js';

// ----------------------
// WorkerContext
// ----------------------

export const WorkerContext = createContext([{ worker: null, ready: false }]);

// ----------------------
// WorkerProvider
// ----------------------

export const WorkerProvider = props => {
  const [worker, setWorker] = createSignal();

  createEffect(() => {
    if (!worker()) {
      setWorker(
        new SharedWorker(
          /* webpackChunkName: "worker" */ new URL('@/worker', import.meta.url)
        )
      );
    }
  });

  onCleanup(() => {
    if (worker()) {
      worker.port.close();
      setWorker(void 0);
    }
  });

  return (
    <WorkerContext.Provider value={[worker]}>
      {props.children}
    </WorkerContext.Provider>
  );
};
